import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Footer from "@/components/layout/Footer";
import { Award, Users, Globe, Heart } from "lucide-react";
export default function AboutPage() {
    return (_jsxs("main", { className: "min-h-screen bg-gray-50", children: [_jsx("section", { className: "bg-gradient-to-r from-blue-600 to-purple-600 py-16 sm:py-20", children: _jsxs("div", { className: "container mx-auto px-4 sm:px-6 text-center text-white", children: [_jsx("h1", { className: "text-3xl sm:text-4xl md:text-5xl font-bold mb-4", children: "About Aurelia Jewels" }), _jsx("p", { className: "text-lg sm:text-xl max-w-3xl mx-auto opacity-90", children: "Crafting timeless elegance since 1995. Your trusted destination for premium jewellery." })] }) }), _jsx("section", { className: "bg-white py-12 sm:py-16", children: _jsx("div", { className: "container mx-auto px-4 sm:px-6", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 items-center", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl sm:text-3xl font-bold text-gray-800 mb-4", children: "Our Story" }), _jsx("p", { className: "text-gray-600 mb-4 leading-relaxed", children: "Founded in 1995, Aurelia Jewels has been at the forefront of luxury jewellery design and craftsmanship. What started as a small family business has grown into one of India's most trusted jewellery brands." }), _jsx("p", { className: "text-gray-600 mb-4 leading-relaxed", children: "We believe that every piece of jewellery tells a story. Our master craftsmen combine traditional techniques with modern design to create pieces that are not just accessories, but heirlooms to be cherished for generations." }), _jsx("p", { className: "text-gray-600 leading-relaxed", children: "With over 50 stores across India and a strong online presence, we continue to serve millions of customers who trust us for their special moments." })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx("img", { src: "/images/rings.jpg", alt: "Craftsmanship", className: "w-full h-48 object-cover rounded-lg" }), _jsx("img", { src: "/images/necklaces.jpg", alt: "Design", className: "w-full h-48 object-cover rounded-lg" }), _jsx("img", { src: "/images/earrings.jpg", alt: "Quality", className: "w-full h-48 object-cover rounded-lg" }), _jsx("img", { src: "/images/bracelets.jpg", alt: "Elegance", className: "w-full h-48 object-cover rounded-lg" })] })] }) }) }), _jsx("section", { className: "bg-gray-50 py-12 sm:py-16", children: _jsxs("div", { className: "container mx-auto px-4 sm:px-6", children: [_jsx("h2", { className: "text-2xl sm:text-3xl font-bold text-gray-800 mb-8 text-center", children: "Our Values" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6", children: [
                                { icon: _jsx(Award, { size: 40 }), title: 'Quality', desc: '100% certified and hallmarked jewellery' },
                                { icon: _jsx(Users, { size: 40 }), title: 'Trust', desc: 'Serving 1M+ happy customers' },
                                { icon: _jsx(Globe, { size: 40 }), title: 'Sustainability', desc: 'Ethically sourced materials' },
                                { icon: _jsx(Heart, { size: 40 }), title: 'Passion', desc: 'Crafted with love and care' },
                            ].map((value, i) => (_jsxs("div", { className: "bg-white p-6 rounded-lg text-center hover:shadow-lg transition-shadow", children: [_jsx("div", { className: "flex justify-center text-blue-600 mb-4", children: value.icon }), _jsx("h3", { className: "font-bold text-lg text-gray-800 mb-2", children: value.title }), _jsx("p", { className: "text-sm text-gray-600", children: value.desc })] }, i))) })] }) }), _jsx("section", { className: "bg-white py-12 sm:py-16", children: _jsx("div", { className: "container mx-auto px-4 sm:px-6", children: _jsx("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-6 text-center", children: [
                            { number: '30+', label: 'Years of Excellence' },
                            { number: '50+', label: 'Stores Nationwide' },
                            { number: '1M+', label: 'Happy Customers' },
                            { number: '10K+', label: 'Unique Designs' },
                        ].map((stat, i) => (_jsxs("div", { className: "p-6", children: [_jsx("div", { className: "text-3xl sm:text-4xl font-bold text-blue-600 mb-2", children: stat.number }), _jsx("div", { className: "text-sm sm:text-base text-gray-600", children: stat.label })] }, i))) }) }) }), _jsx(Footer, {})] }));
}
